DROP TABLE TDMADM.TDM_CAT_USUARIO;
DROP TABLE TDMADM.TDM_CAT_TIPO_USUARIO;
DROP TABLE TDMADM.TDM_CAT_TIPO_TAREA;
DROP TABLE TDMADM.TDM_CAT_TAREA;
DROP TABLE TDMADM.TDM_REL_ASIGNACION_TAREAS;
DROP TABLE TDMADM.TDM_REL_REGISTRO_TAREAS;

CREATE TABLE TDMADM.TDM_CAT_USUARIO (
    ID_USUARIO NUMBER NOT NULL,
    ID_TIPO_USUARIO NUMBER NOT NULL,
    CVE_RESPONSABLE VARCHAR2(10) NOT NULL,
    CVE_USUARIO VARCHAR2(20) NOT NULL,
    DESC_USUARIO VARCHAR2(100) NOT NULL,
    CONTRASENA VARCHAR2(40) NOT NULL,
    ACTIVO NUMBER(1),
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER
) TABLESPACE TS_TDM_DATA;

CREATE UNIQUE INDEX TDMADM.XPKTDM_CAT_USUARIO ON TDMADM.TDM_CAT_USUARIO (ID_USUARIO ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

ALTER TABLE TDMADM.TDM_CAT_USUARIO
    ADD CONSTRAINT XPKTDM_CAT_USUARIO PRIMARY KEY (ID_USUARIO);

----GRANT SELECT, INSERT, UPDATE ON TDMADM.TDM_CAT_USUARIO TO USRTDM;

CREATE TABLE TDMADM.TDM_CAT_TIPO_USUARIO (
    ID_TIPO_USUARIO NUMBER NOT NULL,
    DESC_TIPO_USUARIO VARCHAR2(100) NOT NULL,
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE
) TABLESPACE TS_TDM_DATA;

CREATE UNIQUE INDEX TDMADM.XPKTDM_CAT_TIPO_USUARIO ON TDMADM.TDM_CAT_TIPO_USUARIO (ID_TIPO_USUARIO ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

ALTER TABLE TDMADM.TDM_CAT_TIPO_USUARIO
    ADD CONSTRAINT XPKTDM_CAT_TIPO_USUARIO PRIMARY KEY (ID_TIPO_USUARIO);

----GRANT SELECT, INSERT, UPDATE ON TDMADM.TDM_CAT_TIPO_USUARIO TO USRTDM;

CREATE TABLE TDMADM.TDM_CAT_TIPO_TAREA (
    ID_TIPO_TAREA NUMBER NOT NULL,
    CVE_TIPO_TAREA VARCHAR2(30) NOT NULL,
    DESC_TIPO_TAREA VARCHAR2(60) NOT NULL,
    IMAGEN VARCHAR2(100),
    ORDEN NUMBER,
    ACTIVO NUMBER(1),
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER
) TABLESPACE TS_TDM_DATA;

CREATE UNIQUE INDEX TDMADM.XPKTDM_CAT_TIPO_TAREA ON TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

ALTER TABLE TDMADM.TDM_CAT_TIPO_TAREA
    ADD CONSTRAINT XPKTDM_CAT_TIPO_TAREA PRIMARY KEY (ID_TIPO_TAREA);

----GRANT SELECT ON TDMADM.TDM_CAT_TIPO_TAREA TO USRTDM;

CREATE TABLE TDMADM.TDM_CAT_TAREA (
    ID_TAREA NUMBER NOT NULL,
    CVE_TAREA VARCHAR2(30) NOT NULL,
    DESC_TAREA VARCHAR2(60) NOT NULL,
    OBSERVACIONES VARCHAR2(200),
    ID_TIPO_TAREA NUMBER NOT NULL,
    ID_TAREA_PADRE NUMBER,
    NIVEL NUMBER,
    ID_RESPONSABLE NUMBER,
    ESTATUS NUMBER(1),
    ACTIVO NUMBER(1),
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER    
) TABLESPACE TS_TDM_DATA;

CREATE UNIQUE INDEX TDMADM.XPKTDM_CAT_TAREA ON TDMADM.TDM_CAT_TAREA (ID_TAREA ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

ALTER TABLE TDMADM.TDM_CAT_TAREA
    ADD CONSTRAINT XPKTDM_CAT_TAREA PRIMARY KEY (ID_TAREA);

----GRANT SELECT, INSERT, UPDATE ON TDMADM.TDM_CAT_TAREA TO USRTDM;

CREATE TABLE TDMADM.TDM_REL_ASIGNACION_TAREAS (
    ID_TAREA NUMBER NOT NULL,
    ID_RESPONSABLE NUMBER,
    HORAS_PRESUPUESTO NUMBER,
    HORAS_ESTIMADO NUMBER,
    HORAS_APLICADAS NUMBER,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER        
) TABLESPACE TS_TDM_DATA;

CREATE INDEX TDMADM.IDX1TDM_REL_ASIGNACION_TAREAS ON TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

CREATE INDEX TDMADM.IDX2TDM_REL_ASIGNACION_TAREAS ON TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_RESPONSABLE ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);
a
--GRANT SELECT, INSERT, UPDATE ON TDMADM.TDM_REL_ASIGNACION_TAREAS TO USRTDM;

CREATE TABLE TDMADM.TDM_REL_REGISTRO_TAREAS (
    ID_TAREA NUMBER NOT NULL,
    ID_RESPONSABLE NUMBER NOT NULL,
    OBSERVACIONES VARCHAR2(1000),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    HORAS_APLICADAS NUMBER NOT NULL,
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER
) TABLESPACE TS_TDM_DATA;

--GRANT SELECT, INSERT, UPDATE ON TDMADM.TDM_REL_REGISTRO_TAREAS TO USRTDM;

CREATE TABLE TDMADM.TDM_CONF_PARAMETROS(
    ID_PARAMETRO NUMBER NOT NULL,
    DESC_PARAMETRO VARCHAR2(100),
    VALOR1 VARCHAR2(1000),
    VALOR2 VARCHAR2(1000)
) TABLESPACE TS_TDM_DATA;

CREATE UNIQUE INDEX TDMADM.XPKTDM_CONF_PARAMETROS ON TDMADM.TDM_CONF_PARAMETROS (ID_PARAMETRO ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

ALTER TABLE TDMADM.TDM_CONF_PARAMETROS
    ADD CONSTRAINT XPKTDM_CONF_PARAMETROS PRIMARY KEY (ID_PARAMETRO);

----GRANT SELECT, INSERT, UPDATE ON TDMADM.TDM_CAT_TIPO_USUARIO TO USRTDM;

--------------- Insercion de Datos  -----------------------
-- Usuarios --
INSERT INTO TDMADM.TDM_CAT_USUARIO (ID_USUARIO, CVE_RESPONSABLE, CVE_USUARIO, DESC_USUARIO, CONTRASENA, ACTIVO, INDICADOR, FECHA_CREACION)
SELECT (SELECT COALESCE(MAX(ID_USUARIO), 0)+1 FROM TDMADM.TDM_CAT_USUARIO) AS ID_USUARIO, 'OMA', 'omar.martinez', 'Omar Martínez Castillo', '123', 1, 1, SYSDATE FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA');

COMMIT;

-- Tipos de Tarea --
INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'PROY', 'Proyecto', 'C:\123.jpg', 1, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'BIT', 'Bitácora', 'C:\123.jpg', 2, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'BIT');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'ASIG', 'Asignación', 'C:\123.jpg', 3, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'ASIG');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'SUP', 'Supervisión', 'C:\123.jpg', 4, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'SUP');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'CAP', 'Capacitación', 'C:\123.jpg', 5, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'CAP');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'VTAS', 'Ventas', 'C:\123.jpg', 6, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'VTAS');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'RH', 'Recursos Humanos', 'C:\123.jpg', 7, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'RH');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'ADM', 'Administración', 'C:\123.jpg', 8, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'ADM');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'PERS', 'Personal', 'C:\123.jpg', 9, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PERS');

INSERT INTO TDMADM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'SASIG', 'Sin Tareas', 'C:\123.jpg', 10, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'SASIG');

COMMIT;

-- Tareas --
INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'ASIG', 'Asignación', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'ASIG') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'ASIG');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'SUP', 'Supervisión', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'SUP') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SUP');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'VTAS', 'Apoyo a Ventas', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'VTAS') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'VTAS');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'RH', 'Recursos Humanos', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'RH') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'RH');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'ADM', 'Administración', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'ADM') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'ADM');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PERS', 'Personal', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PERS') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PERS');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'SASIG', 'Sin Tareas', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'SASIG') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SASIG');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY', 'Proyectos', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SASIG');

COMMIT;

-- Asignacion Tareas --
INSERT INTO TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SUP'), (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SUP') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

INSERT INTO TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'VTAS'), (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'VTAS') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

INSERT INTO TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'RH'), (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'RH') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

INSERT INTO TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PERS'), (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PERS') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

INSERT INTO TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SASIG'), (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SASIG') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));


INSERT INTO "TDMADM"."TDM_CAT_TIPO_USUARIO" (ID_TIPO_USUARIO, DESC_TIPO_USUARIO, INDICADOR, FECHA_CREACION) VALUES ('3', 'Programador', '1', TO_DATE('2016-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "TDMADM"."TDM_CAT_TIPO_USUARIO" (ID_TIPO_USUARIO, DESC_TIPO_USUARIO, INDICADOR, FECHA_CREACION) VALUES ('2', 'Lider', '1', TO_DATE('2016-04-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
INSERT INTO "TDMADM"."TDM_CAT_TIPO_USUARIO" (ID_TIPO_USUARIO, DESC_TIPO_USUARIO, INDICADOR, FECHA_CREACION) VALUES ('1', 'Administrador', '1', TO_DATE('2016-04-15 04:05:40', 'YYYY-MM-DD HH24:MI:SS'))

INSERT INTO "TDMADM"."TDM_CONF_PARAMETROS" (ID_PARAMETRO, DESC_PARAMETRO, VALOR1, VALOR2) VALUES ('1', 'DEFAULT_PASSWORD', 'dotech','14151035045510542433344112003343555302350532123021')

COMMIT;