DROP TABLE ADMTDM.TDM_CAT_USUARIO;
DROP TABLE ADMTDM.TDM_CAT_TIPO_TAREA;
DROP TABLE ADMTDM.TDM_CAT_TAREA;
DROP TABLE ADMTDM.TDM_REL_ASIGNACION_TAREAS;
DROP TABLE ADMTDM.TDM_REL_REGISTRO_TAREAS;

CREATE TABLE ADMTDM.TDM_CAT_USUARIO (
    ID_USUARIO NUMBER NOT NULL,
    CVE_RESPONSABLE VARCHAR2(10) NOT NULL,
    CVE_USUARIO VARCHAR2(20) NOT NULL,
    DESC_USUARIO VARCHAR2(100) NOT NULL,
    CONTRASENA VARCHAR2(40) NOT NULL,
    ACTIVO NUMBER(1),
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER
) TABLESPACE TS_TDM_DATA;

CREATE UNIQUE INDEX ADMTDM.XPKTDM_CAT_USUARIO ON ADMTDM.TDM_CAT_USUARIO (ID_USUARIO ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

ALTER TABLE ADMTDM.TDM_CAT_USUARIO
    ADD CONSTRAINT XPKTDM_CAT_USUARIO PRIMARY KEY (ID_USUARIO);

GRANT SELECT, INSERT, UPDATE ON ADMTDM.TDM_CAT_USUARIO TO USRTDM;

CREATE TABLE ADMTDM.TDM_CAT_TIPO_TAREA (
    ID_TIPO_TAREA NUMBER NOT NULL,
    CVE_TIPO_TAREA VARCHAR2(30) NOT NULL,
    DESC_TIPO_TAREA VARCHAR2(60) NOT NULL,
    IMAGEN VARCHAR2(100),
    ORDEN NUMBER,
    ACTIVO NUMBER(1),
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER
) TABLESPACE TS_TDM_DATA;

CREATE UNIQUE INDEX ADMTDM.XPKTDM_CAT_TIPO_TAREA ON ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

ALTER TABLE ADMTDM.TDM_CAT_TIPO_TAREA
    ADD CONSTRAINT XPKTDM_CAT_TIPO_TAREA PRIMARY KEY (ID_TIPO_TAREA);

GRANT SELECT ON ADMTDM.TDM_CAT_TIPO_TAREA TO USRTDM;

CREATE TABLE ADMTDM.TDM_CAT_TAREA (
    ID_TAREA NUMBER NOT NULL,
    CVE_TAREA VARCHAR2(30) NOT NULL,
    DESC_TAREA VARCHAR2(60) NOT NULL,
    OBSERVACIONES VARCHAR2(200),
    ID_TIPO_TAREA NUMBER NOT NULL,
    ID_TAREA_PADRE NUMBER,
    NIVEL NUMBER,
    ID_RESPONSABLE NUMBER,
    ACTIVO NUMBER(1),
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER    
) TABLESPACE TS_TDM_DATA;

CREATE UNIQUE INDEX ADMTDM.XPKTDM_CAT_TAREA ON ADMTDM.TDM_CAT_TAREA (ID_TAREA ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

ALTER TABLE ADMTDM.TDM_CAT_TAREA
    ADD CONSTRAINT XPKTDM_CAT_TAREA PRIMARY KEY (ID_TAREA);

GRANT SELECT, INSERT, UPDATE ON ADMTDM.TDM_CAT_TAREA TO USRTDM;

CREATE TABLE ADMTDM.TDM_REL_ASIGNACION_TAREAS (
    ID_TAREA NUMBER NOT NULL,
    ID_RESPONSABLE NUMBER,
    HORAS_PRESUPUESTO NUMBER,
    HORAS_ESTIMADO NUMBER,
    HORAS_APLICADAS NUMBER,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER        
) TABLESPACE TS_TDM_DATA;

CREATE INDEX ADMTDM.IDX1TDM_REL_ASIGNACION_TAREAS ON ADMTDM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

CREATE INDEX ADMTDM.IDX2TDM_REL_ASIGNACION_TAREAS ON ADMTDM.TDM_REL_ASIGNACION_TAREAS (ID_RESPONSABLE ASC)
TABLESPACE TS_TDM_INDEX storage(initial 512K next 512K);

GRANT SELECT, INSERT, UPDATE ON ADMTDM.TDM_REL_ASIGNACION_TAREAS TO USRTDM;

CREATE TABLE ADMTDM.TDM_REL_REGISTRO_TAREAS (
    ID_TAREA NUMBER NOT NULL,
    ID_RESPONSABLE NUMBER NOT NULL,
    OBSERVACIONES VARCHAR2(1000),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    HORAS_APLICADAS NUMBER NOT NULL,
    INDICADOR NUMBER(1),
    FECHA_CREACION DATE NOT NULL,
    ID_USUARIO_CREACION NUMBER,
    FECHA_MODIFICACION DATE,
    ID_USUARIO_MODIFICACION NUMBER
) TABLESPACE TS_TDM_DATA;

GRANT SELECT, INSERT, UPDATE ON ADMTDM.TDM_REL_REGISTRO_TAREAS TO USRTDM;

--------------- Insercion de Datos  -----------------------
-- Usuarios --
INSERT INTO ADMTDM.TDM_CAT_USUARIO (ID_USUARIO, CVE_RESPONSABLE, CVE_USUARIO, DESC_USUARIO, CONTRASENA, ACTIVO, INDICADOR, FECHA_CREACION)
SELECT (SELECT COALESCE(MAX(ID_USUARIO), 0)+1 FROM ADMTDM.TDM_CAT_USUARIO) AS ID_USUARIO, 'OMA', 'omar.martinez', 'Omar Martínez Castillo', '123', 1, 1, SYSDATE FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA');

COMMIT;

-- Tipos de Tarea --
INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'PROY', 'Proyecto', 'C:\123.jpg', 1, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'BIT', 'Bitácora', 'C:\123.jpg', 2, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'BIT');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'ASIG', 'Asignación', 'C:\123.jpg', 3, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'ASIG');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'SUP', 'Supervisión', 'C:\123.jpg', 4, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'SUP');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'CAP', 'Capacitación', 'C:\123.jpg', 5, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'CAP');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'VTAS', 'Ventas', 'C:\123.jpg', 6, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'VTAS');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'RH', 'Recursos Humanos', 'C:\123.jpg', 7, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'RH');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'ADM', 'Administración', 'C:\123.jpg', 8, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'ADM');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'PERS', 'Personal', 'C:\123.jpg', 9, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PERS');

INSERT INTO ADMTDM.TDM_CAT_TIPO_TAREA (ID_TIPO_TAREA, CVE_TIPO_TAREA, DESC_TIPO_TAREA, IMAGEN, ORDEN, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TIPO_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TIPO_TAREA) AS ID_TIPO_TAREA, 'SASIG', 'Sin Tareas', 'C:\123.jpg', 10, 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'SASIG');

COMMIT;

-- Tareas --
INSERT INTO ADMTDM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TAREA) AS ID_TAREA, 'ASIG', 'Asignación', (SELECT MAX(ID_TIPO_TAREA) FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'ASIG') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'ASIG');

INSERT INTO ADMTDM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TAREA) AS ID_TAREA, 'SUP', 'Supervisión', (SELECT MAX(ID_TIPO_TAREA) FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'SUP') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SUP');

INSERT INTO ADMTDM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TAREA) AS ID_TAREA, 'VTAS', 'Apoyo a Ventas', (SELECT MAX(ID_TIPO_TAREA) FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'VTAS') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'VTAS');

INSERT INTO ADMTDM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TAREA) AS ID_TAREA, 'RH', 'Recursos Humanos', (SELECT MAX(ID_TIPO_TAREA) FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'RH') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'RH');

INSERT INTO ADMTDM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TAREA) AS ID_TAREA, 'ADM', 'Administración', (SELECT MAX(ID_TIPO_TAREA) FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'ADM') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'ADM');

INSERT INTO ADMTDM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TAREA) AS ID_TAREA, 'PERS', 'Personal', (SELECT MAX(ID_TIPO_TAREA) FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PERS') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PERS');

INSERT INTO ADMTDM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, DESC_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM ADMTDM.TDM_CAT_TAREA) AS ID_TAREA, 'SASIG', 'Sin Tareas', (SELECT MAX(ID_TIPO_TAREA) FROM ADMTDM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'SASIG') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SASIG');

COMMIT;

-- Asignacion Tareas --
INSERT INTO ADMTDM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SUP'), (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SUP') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

INSERT INTO ADMTDM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'VTAS'), (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'VTAS') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

INSERT INTO ADMTDM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'RH'), (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'RH') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

INSERT INTO ADMTDM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PERS'), (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PERS') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

INSERT INTO ADMTDM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SASIG'), (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), SYSDATE, (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMTDM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM ADMTDM.TDM_CAT_TAREA WHERE CVE_TAREA = 'SASIG') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM ADMTDM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

COMMIT;