--**** INSERTS DE VALORES MUESTRA****

--SIADM.USERS
INSERT INTO  SIADM.USERS(ID_USER, USERNAME, PASSWORD, ID_PROFILE, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 1, 'melissa.lopez', 'ssitesm', 1, 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.USERS WHERE ID_USER = 1);

INSERT INTO  SIADM.USERS(ID_USER, USERNAME, PASSWORD, ID_PROFILE, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 2, 'manuel.calzado', 'ssitesm', 1, 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 2 FROM  SIADM.USERS WHERE ID_USER = 2);

INSERT INTO  SIADM.USERS(ID_USER, USERNAME, PASSWORD, ID_PROFILE, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 3, 'liliana.gonzalez', 'ssitesm', 2, 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 3 FROM  SIADM.USERS WHERE ID_USER = 3);

--SIADM.PROFILES
INSERT INTO  SIADM.PROFILES(ID_PROFILE, DESC_PROFILE)
SELECT 1, 'Administrador'FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.PROFILES WHERE ID_PROFILE = 1);

INSERT INTO  SIADM.PROFILES(ID_PROFILE, DESC_PROFILE)
SELECT 2, 'Usuario' FROM DUAL 
WHERE NOT EXISTS (SELECT 2 FROM  SIADM.PROFILES WHERE ID_PROFILE = 2);

--SIADM.STUDENTS
INSERT INTO  SIADM.STUDENTS(ID_STUDENT, STUDENT_NUMBER, FIRST_NAME, LAST_NAME, BACHELOR, EMAIL, PHONE_NUMBER, COMMENTS, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 1, 'A00811101', 'Eduardo', 'Bertaud', 'ITC', 'eduardo@gmail.com', 8110354881, 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum', 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.STUDENTS WHERE ID_STUDENT = 1);

INSERT INTO  SIADM.STUDENTS(ID_STUDENT, STUDENT_NUMBER, FIRST_NAME, LAST_NAME, BACHELOR, EMAIL, PHONE_NUMBER, COMMENTS, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 2, 'A00811102', 'Luis', 'Loera', 'ISD', 'luis@gmail.com', 8110354882, 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum', 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 2 FROM  SIADM.STUDENTS WHERE ID_STUDENT = 2);

INSERT INTO  SIADM.STUDENTS(ID_STUDENT, STUDENT_NUMBER, FIRST_NAME, LAST_NAME, BACHELOR, EMAIL, PHONE_NUMBER, COMMENTS, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 3, 'A00811103', 'Alejandra', 'Garza', 'ARQ', 'ale@gmail.com', 8110354883, 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum', 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 3 FROM  SIADM.STUDENTS WHERE ID_STUDENT = 3);

--SIADM.ASSOCIATIONS
INSERT INTO  SIADM.ASSOCIATIONS(ID_ASSOCIATION, ASSOCIATION_NAME, EMAIL, PHONE_NUMBER, COMMENTS, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 1, 'MiniRobotica', 'minirobotica@gmail.com', 8110354811, 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum', 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.ASSOCIATIONS WHERE ID_ASSOCIATION = 1);

INSERT INTO  SIADM.ASSOCIATIONS(ID_ASSOCIATION, ASSOCIATION_NAME, EMAIL, PHONE_NUMBER, COMMENTS, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 2, 'Edifica', 'edifica@gmail.com', 8110354812, 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum', 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 2 FROM  SIADM.ASSOCIATIONS WHERE ID_ASSOCIATION = 2);

--SIADM.REL_STUDENT_ASSOCIATION
INSERT INTO  SIADM.REL_STUDENT_ASSOCIATION(ID_STUDENT, ID_ASSOCIATION)
SELECT 1,1 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.REL_STUDENT_ASSOCIATION WHERE ID_STUDENT = 1 AND ID_ASSOCIATION = 1);

INSERT INTO  SIADM.REL_STUDENT_ASSOCIATION(ID_STUDENT, ID_ASSOCIATION)
SELECT 3,2 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.REL_STUDENT_ASSOCIATION WHERE ID_STUDENT = 3 AND ID_ASSOCIATION = 2);

--SIADM.PROJECTS
INSERT INTO  SIADM.PROJECTS(ID_PROJECT, PROJECT_NAME, DESC_PROJECT, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 1, 'Construyendo Viviendas', 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum', 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.PROJECTS WHERE ID_PROJECT = 1);

INSERT INTO  SIADM.PROJECTS(ID_PROJECT, PROJECT_NAME, DESC_PROJECT, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 2, 'PrepaNet', 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum', 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.PROJECTS WHERE ID_PROJECT = 2);

INSERT INTO  SIADM.PROJECTS(ID_PROJECT, PROJECT_NAME, DESC_PROJECT, ACTIVE, USER_MODIFY, CREATION_DATE)
SELECT 3, 'MexicoRural', 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum', 1, null, SYSDATE FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.PROJECTS WHERE ID_PROJECT = 3);

--SIADM.MEMBER_TYPES
INSERT INTO  SIADM.MEMBER_TYPES(ID_MEMBER_TYPE, DESC_MEMBER_TYPE)
SELECT 1, 'Estudiante Destacado' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.MEMBER_TYPES WHERE ID_MEMBER_TYPE = 1);

INSERT INTO  SIADM.MEMBER_TYPES(ID_MEMBER_TYPE, DESC_MEMBER_TYPE)
SELECT 2, 'Grupo Estudiantil Destacado' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.MEMBER_TYPES WHERE ID_MEMBER_TYPE = 2);

--SIADM.REL_MEMBER_PROJECT
INSERT INTO  SIADM.REL_MEMBER_PROJECT(ID_MEMBER, ID_MEMBER_TYPE, ID_PROJECT)
SELECT 2, 1, 3 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.REL_MEMBER_PROJECT WHERE ID_MEMBER = 2 AND ID_MEMBER_TYPE = 1 AND ID_PROJECT = 3);

INSERT INTO  SIADM.REL_MEMBER_PROJECT(ID_MEMBER, ID_MEMBER_TYPE, ID_PROJECT)
SELECT 1, 1, 2 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.REL_MEMBER_PROJECT WHERE ID_MEMBER = 1 AND ID_MEMBER_TYPE = 1 AND ID_PROJECT = 2);

INSERT INTO  SIADM.REL_MEMBER_PROJECT(ID_MEMBER, ID_MEMBER_TYPE, ID_PROJECT)
SELECT 2, 2, 1 FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM  SIADM.REL_MEMBER_PROJECT WHERE ID_MEMBER = 2 AND ID_MEMBER_TYPE = 2 AND ID_PROJECT = 1);

COMMIT;