-- Insertar proyecto
INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY0001', 'Proyecto Pueba', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, 8, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0001');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY000101', 'Analisis', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0001'), 2, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000101');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY000102', 'Diseño Conceptual', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0001'), 2, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000102');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY000103', 'Diseño Detallado', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0001'), 2, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000103');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY000104', 'Construcción', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0001'), 2, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000104');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY00010401', 'Programa 1', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000104'), 3, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY00010401');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA, OBSERVACIONES, ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY00010402', 'Programa 2', 'Revisar a detalle las tareas para dar un seguimiento oportuno', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000104'), 3, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY00010402');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY000105', 'Pruebas', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0001'), 2, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000105');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY000106', 'Entrega', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0001'), 2, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000106');

COMMIT;

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY0002', 'Proyecto Pueba 2', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, 1, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0002');

INSERT INTO TDMADM.TDM_CAT_TAREA (ID_TAREA, CVE_TAREA, NOMBRE_TAREA,  ID_TIPO_TAREA, ID_TAREA_PADRE, NIVEL, ID_RESPONSABLE, ACTIVO, INDICADOR, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT COALESCE(MAX(ID_TAREA), 0)+1 FROM TDMADM.TDM_CAT_TAREA) AS ID_TAREA, 'PROY000201', 'Analisis', (SELECT MAX(ID_TIPO_TAREA) FROM TDMADM.TDM_CAT_TIPO_TAREA WHERE CVE_TIPO_TAREA = 'PROY') AS ID_TIPO_TAREA, (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY0002'), 2, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 1, 1, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000201');

-- Asignacion Tareas --
INSERT INTO TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, HORAS_PRESUPUESTO, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY00010401'), (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 5/60, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY00010401') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

COMMIT;

INSERT INTO TDMADM.TDM_REL_ASIGNACION_TAREAS (ID_TAREA, ID_RESPONSABLE, HORAS_PRESUPUESTO, FECHA_CREACION, ID_USUARIO_CREACION)
SELECT (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000201'), (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'), 5/60, SYSDATE, (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TDMADM.TDM_REL_ASIGNACION_TAREAS WHERE ID_TAREA = (SELECT MAX(ID_TAREA) FROM TDMADM.TDM_CAT_TAREA WHERE CVE_TAREA = 'PROY000201') AND ID_RESPONSABLE = (SELECT MAX(ID_USUARIO) FROM TDMADM.TDM_CAT_USUARIO WHERE CVE_RESPONSABLE = 'OMA'));

COMMIT;